server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

models.path.ru.sent=models/ru-sent.bin
models.path.ru.token=models/ru-token.bin
models.path.en.sent=models/en-sent.bin
models.path.en.token=models/en-token.bin

corpus.path=corpus/